package com.example.eudi_wallet_exploration_backend.model

/**
 * Represents a credential offer generated by the Issuer to initiate the OIDC4VCI flow.
 *
 * Serialised as a JSON-encoded query parameter on an `openid-credential-offer://` URI, which the wallet receives
 * either by scanning a QR code or via a deep link. Contains the issuer's base URL, the credential type being offered,
 * and the grant used to obtain and access token &mdash; in this case a pre-authorised code.
 */
data class CredentialOffer()
