package com.example.eudi_wallet_exploration_backend.store

import org.springframework.stereotype.Component

/**
 * A `@Component` backend by a `ConcurrentHashMap`. Stores nonces generated by the Verifier for active presentation
 * requests. Provides `store()`, `consume()` (validates and removes in one operation to prevent replay), and `exists()`
 * methods.
 */
@Component
class NonceStore {
}